"""Stable, non-secret CASE runtime defaults safe to commit."""

CASE_VOICE_MODE = "classic"
REALTIME_PROVIDER = "gemini_live"
GEMINI_LIVE_MODEL = "gemini-2.5-flash-native-audio-preview-12-2025"
GEMINI_LIVE_VOICE_NAME = "Schedar"
GEMINI_TEXT_MODEL = "gemini-3.1-flash-lite"
CASE_REALTIME_VOICE_PERSONA = "case_mate_deadpan_v1"
CASE_VOICE_PRESET = "case_mate_deadpan_v1"
CASE_STYLE_SHORT_REPLIES = True
CASE_STYLE_MAX_SENTENCES = 3
CASE_HUMOR_PERCENT = 65
CASE_HONESTY_PERCENT = 90
CASE_SARCASM_LEVEL = "medium"
CASE_VOICE_PIPELINE = "hybrid_text_tts"
VOICE_OUTPUT_BACKEND = "piper_onnx"
PIPER_MODEL_PATH = "models/voices/CASE.onnx"
PIPER_CONFIG_PATH = "models/voices/CASE.onnx.json"
PIPER_LENGTH_SCALE = 1.0
PIPER_NOISE_SCALE = 0.667
PIPER_NOISE_W = 0.8
CASE_AUDIO_INPUT_DEVICE = ""
CASE_AUDIO_OUTPUT_DEVICE = ""
AUDIO_PLAYBACK_BACKEND = "sounddevice"
AUDIO_OUTPUT_DEVICE = ""
AUDIO_OUTPUT_SAMPLE_RATE = 44_100
AUDIO_OUTPUT_CHANNELS = 2
AUDIO_PLAYBACK_LATENCY = "high"
AUDIO_PLAYBACK_BLOCKSIZE = 0
AUDIO_PLAYBACK_KEEP_STREAM_OPEN = True
AUDIO_PLAYBACK_TAIL_GUARD_SEC = 0.12
AUDIO_SHORT_SOUND_SAFE_MODE = True
AUDIO_SHORT_SOUND_THRESHOLD_SEC = 1.8
AUDIO_SHORT_SOUND_EXTRA_TAIL_MS = 300
GEMINI_LIVE_NATIVE_AUDIO_ENABLED = False
CASE_STT_PROFILE = "balanced"
CASE_STT_FINAL_BACKEND = "auto"
CASE_STT_FINAL_TIMEBOX_SEC = 2.5
CASE_STT_LGRAPH_FINAL_TIMEOUT_SEC = CASE_STT_FINAL_TIMEBOX_SEC
CASE_STT_ACCEPT_FAST_CANDIDATE_ON_TIMEOUT = True
CASE_STT_GLOSSARY_REPAIR = True
CASE_STT_GLOSSARY_PATH = "config/stt_domain_glossary.json"
TRANSCRIPT_INPUT_BACKEND = "vosk_lgraph"
VOSK_LGRAPH_MODEL_PATH = "ai/stt/vosk-model-en-us-0.22-lgraph"
VOSK_SMALL_MODEL_PATH = "ai/stt/vosk-model-small-en-us-0.15"
VOSK_FULL_MODEL_PATH = "ai/stt/vosk-model-en-us-0.22"
SHERPA_SENSEVOICE_MODEL_DIR = (
    "ai/stt/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17"
)
STT_USE_SILERO_VAD = True
SILERO_VAD_MODEL_PATH = "ai/stt/silero_vad.onnx"
SILERO_VAD_THRESHOLD = 0.5
SILERO_VAD_MIN_SPEECH_MS = 250
SILERO_VAD_MIN_SILENCE_MS = 700
SILERO_VAD_SPEECH_PAD_MS = 300
STT_USE_SMART_TURN = True
SMART_TURN_MODEL_PATH = "ai/stt/smart-turn-v3.2-cpu.onnx"
SMART_TURN_THRESHOLD = 0.55
SMART_TURN_MAX_WAIT_SEC = 0.6
SMART_TURN_MIN_AUDIO_SEC = 1.0
SMART_TURN_HOLD_SEC = 1.5
SMART_TURN_ACCEPT_IMMEDIATELY_IF_COMPLETE = True
SMART_TURN_FAST_ACCEPT_PROBABILITY = 0.90
STT_USE_GTCRN_DENOISER = False
GTCRN_MODEL_PATH = "ai/stt/gtcrn_simple.onnx"
HYBRID_TEXT_TTS_ENABLED = True
HYBRID_TEXT_TTS_STREAMING = True
HYBRID_LATENCY_PROFILE = "fast"
HYBRID_MUTE_MIC_DURING_TTS = True
HYBRID_RESUME_MIC_AFTER_TTS_DELAY_SEC = 0.35
HYBRID_STT_SILENCE_SEC = 0.9
HYBRID_STT_CONFIRM_SEC = 0.25
HYBRID_STT_REOPEN_SEC = 0.45
HYBRID_STT_MIN_UTTERANCE_SEC = 0.35
HYBRID_STT_MAX_COMMAND_SEC = 8.0
HYBRID_STT_FOLLOWUP_TIMEOUT_SEC = 4.0
HYBRID_STT_ACCEPT_FINAL_ON_SILENCE = True
HYBRID_STT_DISABLE_REOPEN_AFTER_FINAL = False
HYBRID_WEAK_ENDING_ENABLED = True
HYBRID_HOLD_WEAK_ENDING_SEC = 1.5
HYBRID_REJECT_WAKEWORD_ONLY = True
HYBRID_REJECT_TOO_SHORT = True

CASE_RESPONSE_MODE = "streaming_chunks"
CASE_STREAM_FULL_RESPONSE = True
CASE_REALTIME_MAX_SENTENCES = 4
CASE_REALTIME_TARGET_SENTENCES = 2
CASE_REALTIME_MAX_CHARS = 420
CASE_RESPONSE_MAX_TOTAL_CHARS = CASE_REALTIME_MAX_CHARS
CASE_REALTIME_DETAIL_MAX_CHARS = 480
CASE_REALTIME_DETAIL_MAX_CHUNKS = 5
CASE_REALTIME_JOKE_MAX_CHARS = 110
CASE_REALTIME_MAX_CHARS_ROAST = 110
CASE_VOICE_REPLY_MAX_SENTENCES = 2
CASE_VOICE_REPLY_STYLE = "concise_spoken"
CASE_VOICE_JOKE_MAX_SENTENCES = 2
CASE_REALTIME_REQUIRE_COMPLETE_SENTENCE = True
CASE_REALTIME_ALLOW_LONG_ANSWER_WHEN_ASKED = True
CASE_TTS_REALTIME_MODE = "streaming_chunks"
CASE_TTS_CHUNK_MODE = "sentence"
CASE_TTS_CHUNK_POLICY = CASE_TTS_CHUNK_MODE
CASE_TTS_CHUNK_MIN_CHARS = 35
CASE_TTS_MERGE_TINY_CHUNKS = True
CASE_TTS_TINY_CHUNK_MAX_CHARS = 25
CASE_TTS_SINGLE_CHUNK_UNDER_CHARS = 130
CASE_TTS_FIRST_CHUNK_TARGET_CHARS = 40
CASE_TTS_FIRST_CHUNK_MAX_CHARS = 55
CASE_TTS_NORMAL_CHUNK_TARGET_CHARS = 80
CASE_TTS_NORMAL_CHUNK_MAX_CHARS = 110
CASE_TTS_FLUSH_FIRST_ON_SOFT_PUNCTUATION = True
CASE_TTS_CHUNK_IDEAL_MAX_CHARS = 110
CASE_TTS_CHUNK_MAX_CHARS = CASE_TTS_CHUNK_IDEAL_MAX_CHARS
CASE_TTS_CHUNK_ABSOLUTE_MAX_CHARS = 160
CASE_TTS_CHUNK_PREFER_SENTENCE_BOUNDARY = True
CASE_TTS_ALLOW_MULTI_CHUNK = True
CASE_TTS_MAX_CHUNKS_PER_TURN = 4
CASE_TTS_MAX_CHARS = CASE_RESPONSE_MAX_TOTAL_CHARS
CASE_TTS_SYNTH_CONCURRENCY = 1
CASE_TTS_PLAYBACK_CONCURRENCY = 1
CASE_TTS_DROP_OLD_TURN_ON_BARGE_IN = True
CASE_TTS_MAX_CHUNK_CHARS = CASE_TTS_CHUNK_MAX_CHARS
CASE_TTS_MIN_CHUNK_CHARS = CASE_TTS_CHUNK_MIN_CHARS
CASE_TTS_DROP_OVERFLOW_IN_REALTIME = True
CASE_TTS_REALTIME_MAX_CHUNKS = CASE_TTS_MAX_CHUNKS_PER_TURN
CASE_TTS_REALTIME_MAX_CHARS = CASE_TTS_MAX_CHARS
CASE_TTS_REALTIME_MIN_CHARS_BEFORE_SPEAK = CASE_TTS_CHUNK_MIN_CHARS
CASE_TTS_REALTIME_WAIT_FOR_SENTENCE_END = True
CASE_TTS_REALTIME_TRUNCATE_EXTRA = True
CASE_REALTIME_STOP_AFTER_FIRST_SENTENCE = False
CASE_TTS_TEXT_DEADLINE_SEC = 2.5
CASE_REALTIME_TTS_TEXT_DEADLINE_SEC = CASE_TTS_TEXT_DEADLINE_SEC
CASE_TTS_REQUIRE_SAFE_BOUNDARY = True
CASE_TTS_MIN_SAFE_CHARS = 35
CASE_TTS_MAX_WAIT_FOR_SENTENCE_SEC = 3.0
CASE_TTS_ENABLE_THINKING_FALLBACK = False
CASE_TTS_FALLBACK_SHORT_REPLY = "One moment."
CASE_TTS_FALLBACK_ONLY_ON_ERROR = True
CASE_LLM_FIRST_TOKEN_TIMEOUT_SEC = 4.0
CASE_LLM_STREAM_TOTAL_TIMEOUT_SEC = 15.0
CASE_LLM_FALLBACK_TO_FULL_ON_FIRST_TOKEN_TIMEOUT = True
CASE_LLM_ENABLE_WAITING_FILLER = False
CASE_LLM_WAITING_FILLER_TEXT = "One sec."
CASE_LLM_WAITING_FILLER_AFTER_SEC = 2.5
CASE_ENABLE_THINKING_FILLER = True
CASE_THINKING_FILLER_AFTER_SEC = 1.2
CASE_THINKING_FILLER_SIMPLE_AFTER_SEC = 2.2
CASE_THINKING_FILLER_DIR = "assets/audio/fillers"
CASE_THINKING_FILLER_MAX_PER_TURN = 1
CASE_THINKING_FILLER_KEYS = [
    "hmm_let_me_think",
    "hmm_yeah",
    "give_me_a_second",
    "one_sec",
]
CASE_THINKING_FILLER_PREFERRED_KEYS = [
    "hmm_yeah",
    "one_sec",
]
LLM_HARD_TIMEOUT_SEC = CASE_LLM_STREAM_TOTAL_TIMEOUT_SEC
LLM_FIRST_TOKEN_BUDGET_SEC = CASE_LLM_FIRST_TOKEN_TIMEOUT_SEC
CASE_REALTIME_MAX_LLM_WAIT_SEC = CASE_LLM_STREAM_TOTAL_TIMEOUT_SEC
VOICE_ENABLE_AFC = False
VOICE_ENABLE_TOOLS_BY_DEFAULT = False
CASE_TTS_PRE_SILENCE_MS = 60
CASE_TTS_POST_SILENCE_MS = 180
CASE_TTS_FADE_IN_MS = 5
CASE_TTS_FADE_OUT_MS = 25
CASE_TTS_MIN_UTTERANCE_MS = 700
CASE_TTS_DUMP_LAST_UTTERANCE = False
CASE_TTS_DEBUG_DIR = "output/tts_debug"
CASE_SHOW_LATENCY_SUMMARY = False
CASE_TTS_CACHE_ENABLED = True
CASE_TTS_CACHE_DIR = "output/tts_cache"
CASE_TTS_CACHE_COMMON_PHRASES = True
CASE_CHECK_PI_THROTTLE = True

CASE_MEMORY_ENABLED = True
CASE_MEMORY_BACKEND = "sqlite"
CASE_MEMORY_PATH = "data/memory/case_memory.sqlite"
CASE_SESSION_HISTORY_TURNS = 8
CASE_RECENT_JOKES_LIMIT = 20
CASE_RECENT_TOPICS_LIMIT = 20

CASE_ENABLE_SERVER = False
CASE_SERVER_HOST = "127.0.0.1"
CASE_SERVER_PORT = 8765

CASE_VOICE_FX_ENABLED = False
CASE_VOICE_FX_PRESET = "cinematic_robot_v1"
CASE_VOICE_FX_DUMP_WAV = False
CASE_VOICE_FX_DEBUG_DIR = "output/voice_fx_debug"
CASE_VOICE_RESEARCH_DIR = "research/voice_samples"
CASE_VOICE_SAMPLE_TEXT_SET = "case_default"

REALTIME_HALF_DUPLEX = True
REALTIME_MUTE_MIC_DURING_PLAYBACK = True
REALTIME_ENABLE_BARGE_IN = False
REALTIME_RESUME_MIC_AFTER_PLAYBACK_DELAY_SEC = 0.5
REALTIME_BARGE_IN_MIN_SPEECH_MS = 500
REALTIME_BARGE_IN_RMS_THRESHOLD = 2500.0
REALTIME_BARGE_IN_IGNORE_AFTER_PLAYBACK_START_SEC = 1.0
REALTIME_BARGE_IN_COOLDOWN_SEC = 1.5
REALTIME_BARGE_IN_REQUIRE_CONSECUTIVE_FRAMES = 8
REALTIME_AUDIO_CHUNK_LOG_INTERVAL_SEC = 1.0
REALTIME_STATE_LOG_ON_CHANGE_ONLY = True
REALTIME_DUMP_MODEL_AUDIO_WAV = False
REALTIME_DEBUG_AUDIO_DIR = "output/realtime_debug"

REALTIME_WAKE_ACK_ENABLED = True
REALTIME_WAKE_ACK_MODE = "cached_wav"
REALTIME_WAKE_ACK_TEXT = "I'm listening."
REALTIME_WAKE_ACK_RANDOM_ENABLED = True
WAKE_ACK_TEXTS = {
    "yes": "Yes!",
    "im_listening": "I'm listening.",
}
DEFAULT_WAKE_ACK_POOL = [
    "yes",
    "im_listening",
]
OPTIONAL_SHORT_WAKE_ACKS = {
    "go_on": "Go on.",
    "im_here": "I'm here.",
    "say_that_again": "Say that again?",
    "still_with_you": "Still with you.",
    "what": "What?",
    "yeah": "Yeah?",
    "you_called": "You called?",
}
REALTIME_WAKE_ACK_POOL = [
    WAKE_ACK_TEXTS[key] for key in DEFAULT_WAKE_ACK_POOL
]
REALTIME_WAKE_ACK_AVOID_REPEAT = True
WAKE_ACK_RANDOM_ENABLED = True
WAKE_ACK_POOL = REALTIME_WAKE_ACK_POOL
WAKE_ACK_AVOID_REPEAT = True
WAKE_ACK_USE_VOICE_BACKEND = False
WAKE_ACK_MODE = "cached_wav"
WAKE_ACK_RECORDED_ENABLED = False
WAKE_ACK_RECORDED_DIR = "assets/audio/wake_ack/recorded"
WAKE_ACK_RECORDED_RAW_DIR = "assets/audio/wake_ack/recorded_raw"
WAKE_ACK_RECORDED_PROCESSED_DIR = "assets/audio/wake_ack/recorded_processed"
WAKE_ACK_FALLBACK_MODE = "cached_wav"
WAKE_ACK_WAV_DIR = "assets/audio/wake_ack/generated"
WAKE_ACK_GENERATED_DIR = WAKE_ACK_WAV_DIR
WAKE_ACK_ALLOW_SHORT_INTERJECTIONS = False
WAKE_ACK_PROFILE = "clear_short"
WAKE_ACK_PAD_SHORT_AUDIO = True
WAKE_ACK_PRE_SILENCE_MS = 140
WAKE_ACK_POST_SILENCE_MS = 400
WAKE_ACK_FADE_IN_MS = 12
WAKE_ACK_FADE_OUT_MS = 50
WAKE_ACK_MIN_DURATION_MS = 1000
WAKE_ACK_MIN_TOTAL_DURATION_MS = WAKE_ACK_MIN_DURATION_MS
WAKE_ACK_MIN_VOICED_MS = 350
WAKE_ACK_POST_PLAYBACK_PAD_SEC = 0.15
WAKE_ACK_POST_PLAYBACK_GUARD_SEC = 0.20
WAKE_ACK_FORCE_BLOCKING_PLAYBACK = True
WAKE_ACK_EXTRA_RUNTIME_TAIL_MS = 300
WAKE_ACK_PLAYBACK_LATENCY = "high"
AUDIO_PLAYBACK_RETRY_ON_UNDERFLOW = True
VISION_MODE = "on_demand"
VISION_ON_DEMAND_ONLY = True
VISION_ENABLE_YOLO = False
VISION_ENABLE_BACKGROUND = False
VISION_CLOSE_AFTER_REQUEST = True
VISION_OPEN_CAMERA_ON_BOOT = False
VISION_BACKGROUND_TASK_ENABLED = False
VISION_IDLE_GLANCE_ENABLED = False
VISION_SOCIAL_TRACKING_ENABLED = False
VISION_IDLE_USER_GREETING_ENABLED = False
VISION_AUTO_FACE_TRACKING_ENABLED = False
VISION_ENABLED = True
VISION_RUNTIME_ENABLED = False
VISION_SCHEDULER_ENABLED = False
VISION_STARTUP_ENABLED = False
VISION_IDLE_GREETING_ENABLED = False
VISION_IDLE_GREETING_COOLDOWN_AFTER_CONVERSATION_SEC = 20.0
REALTIME_WAKE_ACK_WAV_DIR = WAKE_ACK_WAV_DIR
REALTIME_WAKE_ACK_WAV_PATH = "assets/audio/realtime_wake_ack.wav"
REALTIME_WAKE_ACK_BLOCKS_MIC = True
REALTIME_WAKE_ACK_CONNECT_IN_PARALLEL = True
REALTIME_WAKE_ACK_POST_DELAY_SEC = 0.25
REALTIME_SEND_AUDIO_STREAM_END_ON_MIC_PAUSE = False

CASE_CONSOLE_MODE = "clean"
CASE_CONSOLE_CLEAN_TRANSCRIPT = True
CASE_DEBUG_LOG_FILE = "logs/case_debug.log"
CASE_CONSOLE_LOG_LEVEL = "WARNING"
CASE_FILE_LOG_LEVEL = "DEBUG"
