"""Validated configuration for CASE realtime cloud voice mode."""

from __future__ import annotations

import logging
import re

from src.config import defaults
from src.config.env import (
    get_bool,
    get_float,
    get_int,
    get_str,
    log_secret_status,
)


logger = logging.getLogger(__name__)

CASE_VOICE_MODE = get_str("CASE_VOICE_MODE", defaults.CASE_VOICE_MODE).lower()
REALTIME_PROVIDER = get_str("REALTIME_PROVIDER", defaults.REALTIME_PROVIDER).lower()
GEMINI_LIVE_MODEL = get_str("GEMINI_LIVE_MODEL", defaults.GEMINI_LIVE_MODEL)
GEMINI_TEXT_MODEL = get_str("GEMINI_TEXT_MODEL", defaults.GEMINI_TEXT_MODEL)
GEMINI_LIVE_VOICE_NAME = get_str(
    "GEMINI_LIVE_VOICE_NAME", defaults.GEMINI_LIVE_VOICE_NAME
)
GEMINI_API_KEY = get_str("GEMINI_API_KEY", "")
log_secret_status("GEMINI_API_KEY", GEMINI_API_KEY)

CASE_REALTIME_VOICE_PERSONA = get_str(
    "CASE_REALTIME_VOICE_PERSONA", defaults.CASE_REALTIME_VOICE_PERSONA
)
CASE_VOICE_PRESET = get_str("CASE_VOICE_PRESET", defaults.CASE_VOICE_PRESET)
CASE_STYLE_SHORT_REPLIES = get_bool(
    "CASE_STYLE_SHORT_REPLIES", defaults.CASE_STYLE_SHORT_REPLIES
)
CASE_STYLE_MAX_SENTENCES = get_int(
    "CASE_STYLE_MAX_SENTENCES", defaults.CASE_STYLE_MAX_SENTENCES
)
CASE_HUMOR_PERCENT = get_int("CASE_HUMOR_PERCENT", defaults.CASE_HUMOR_PERCENT)
CASE_HONESTY_PERCENT = get_int("CASE_HONESTY_PERCENT", defaults.CASE_HONESTY_PERCENT)
CASE_SARCASM_LEVEL = get_str("CASE_SARCASM_LEVEL", defaults.CASE_SARCASM_LEVEL)
CASE_VOICE_PIPELINE = get_str(
    "CASE_VOICE_PIPELINE", defaults.CASE_VOICE_PIPELINE
).lower()
VOICE_OUTPUT_BACKEND = get_str(
    "VOICE_OUTPUT_BACKEND", defaults.VOICE_OUTPUT_BACKEND
).lower()
PIPER_MODEL_PATH = get_str("PIPER_MODEL_PATH", defaults.PIPER_MODEL_PATH)
PIPER_CONFIG_PATH = get_str("PIPER_CONFIG_PATH", defaults.PIPER_CONFIG_PATH)
PIPER_LENGTH_SCALE = get_float("PIPER_LENGTH_SCALE", defaults.PIPER_LENGTH_SCALE)
PIPER_NOISE_SCALE = get_float("PIPER_NOISE_SCALE", defaults.PIPER_NOISE_SCALE)
PIPER_NOISE_W = get_float("PIPER_NOISE_W", defaults.PIPER_NOISE_W)
GEMINI_LIVE_NATIVE_AUDIO_ENABLED = get_bool(
    "GEMINI_LIVE_NATIVE_AUDIO_ENABLED",
    get_bool("GEMINI_LIVE_NATIVE_AUDIO", defaults.GEMINI_LIVE_NATIVE_AUDIO_ENABLED),
)
TRANSCRIPT_INPUT_BACKEND = get_str(
    "TRANSCRIPT_INPUT_BACKEND", defaults.TRANSCRIPT_INPUT_BACKEND
).lower()
CASE_STT_PROFILE = get_str(
    "CASE_STT_PROFILE", defaults.CASE_STT_PROFILE
).lower()
CASE_STT_FINAL_BACKEND = get_str(
    "CASE_STT_FINAL_BACKEND", defaults.CASE_STT_FINAL_BACKEND
).lower()
CASE_STT_FINAL_TIMEBOX_SEC = get_float(
    "CASE_STT_FINAL_TIMEBOX_SEC",
    get_float(
        "CASE_STT_LGRAPH_FINAL_TIMEOUT_SEC",
        defaults.CASE_STT_FINAL_TIMEBOX_SEC,
    ),
)
CASE_STT_LGRAPH_FINAL_TIMEOUT_SEC = CASE_STT_FINAL_TIMEBOX_SEC
CASE_STT_ACCEPT_FAST_CANDIDATE_ON_TIMEOUT = get_bool(
    "CASE_STT_ACCEPT_FAST_CANDIDATE_ON_TIMEOUT",
    defaults.CASE_STT_ACCEPT_FAST_CANDIDATE_ON_TIMEOUT,
)
CASE_STT_FINAL_MODE = get_str(
    "CASE_STT_FINAL_MODE",
    defaults.CASE_STT_FINAL_MODE,
).lower()
CASE_STT_GLOSSARY_REPAIR = get_bool(
    "CASE_STT_GLOSSARY_REPAIR",
    defaults.CASE_STT_GLOSSARY_REPAIR,
)
CASE_STT_GLOSSARY_PATH = get_str(
    "CASE_STT_GLOSSARY_PATH",
    defaults.CASE_STT_GLOSSARY_PATH,
)
CASE_CLOUD_STT_PROVIDER = get_str(
    "CASE_CLOUD_STT_PROVIDER",
    defaults.CASE_CLOUD_STT_PROVIDER,
).lower()
CASE_CLOUD_STT_MODEL = get_str(
    "CASE_CLOUD_STT_MODEL",
    defaults.CASE_CLOUD_STT_MODEL,
)
CASE_CLOUD_STT_TIMEOUT_SEC = get_float(
    "CASE_CLOUD_STT_TIMEOUT_SEC",
    defaults.CASE_CLOUD_STT_TIMEOUT_SEC,
)
CASE_CLOUD_STT_FALLBACK = get_str(
    "CASE_CLOUD_STT_FALLBACK",
    defaults.CASE_CLOUD_STT_FALLBACK,
).lower()
CASE_CLOUD_STT_SAVE_DEBUG_AUDIO = get_bool(
    "CASE_CLOUD_STT_SAVE_DEBUG_AUDIO",
    defaults.CASE_CLOUD_STT_SAVE_DEBUG_AUDIO,
)
CASE_CLOUD_STT_DEBUG_DIR = get_str(
    "CASE_CLOUD_STT_DEBUG_DIR",
    defaults.CASE_CLOUD_STT_DEBUG_DIR,
)
VOSK_LGRAPH_MODEL_PATH = get_str(
    "VOSK_LGRAPH_MODEL_PATH", defaults.VOSK_LGRAPH_MODEL_PATH
)
VOSK_SMALL_MODEL_PATH = get_str(
    "VOSK_SMALL_MODEL_PATH", defaults.VOSK_SMALL_MODEL_PATH
)
VOSK_FULL_MODEL_PATH = get_str(
    "VOSK_FULL_MODEL_PATH", defaults.VOSK_FULL_MODEL_PATH
)
SHERPA_SENSEVOICE_MODEL_DIR = get_str(
    "SHERPA_SENSEVOICE_MODEL_DIR", defaults.SHERPA_SENSEVOICE_MODEL_DIR
)
STT_USE_SILERO_VAD = get_bool(
    "STT_USE_SILERO_VAD", defaults.STT_USE_SILERO_VAD
)
SILERO_VAD_MODEL_PATH = get_str(
    "SILERO_VAD_MODEL_PATH", defaults.SILERO_VAD_MODEL_PATH
)
SILERO_VAD_THRESHOLD = get_float(
    "SILERO_VAD_THRESHOLD", defaults.SILERO_VAD_THRESHOLD
)
SILERO_VAD_MIN_SPEECH_MS = get_int(
    "SILERO_VAD_MIN_SPEECH_MS", defaults.SILERO_VAD_MIN_SPEECH_MS
)
SILERO_VAD_MIN_SILENCE_MS = get_int(
    "SILERO_VAD_MIN_SILENCE_MS", defaults.SILERO_VAD_MIN_SILENCE_MS
)
SILERO_VAD_SPEECH_PAD_MS = get_int(
    "SILERO_VAD_SPEECH_PAD_MS", defaults.SILERO_VAD_SPEECH_PAD_MS
)
STT_USE_SMART_TURN = get_bool(
    "STT_USE_SMART_TURN", defaults.STT_USE_SMART_TURN
)
SMART_TURN_MODEL_PATH = get_str(
    "SMART_TURN_MODEL_PATH", defaults.SMART_TURN_MODEL_PATH
)
SMART_TURN_THRESHOLD = get_float(
    "SMART_TURN_THRESHOLD", defaults.SMART_TURN_THRESHOLD
)
SMART_TURN_MAX_WAIT_SEC = get_float(
    "SMART_TURN_MAX_WAIT_SEC", defaults.SMART_TURN_MAX_WAIT_SEC
)
SMART_TURN_MIN_AUDIO_SEC = get_float(
    "SMART_TURN_MIN_AUDIO_SEC", defaults.SMART_TURN_MIN_AUDIO_SEC
)
SMART_TURN_HOLD_SEC = get_float(
    "SMART_TURN_HOLD_SEC", defaults.SMART_TURN_HOLD_SEC
)
SMART_TURN_ACCEPT_IMMEDIATELY_IF_COMPLETE = get_bool(
    "SMART_TURN_ACCEPT_IMMEDIATELY_IF_COMPLETE",
    defaults.SMART_TURN_ACCEPT_IMMEDIATELY_IF_COMPLETE,
)
SMART_TURN_FAST_ACCEPT_PROBABILITY = get_float(
    "SMART_TURN_FAST_ACCEPT_PROBABILITY",
    defaults.SMART_TURN_FAST_ACCEPT_PROBABILITY,
)
STT_USE_GTCRN_DENOISER = get_bool(
    "STT_USE_GTCRN_DENOISER", defaults.STT_USE_GTCRN_DENOISER
)
GTCRN_MODEL_PATH = get_str("GTCRN_MODEL_PATH", defaults.GTCRN_MODEL_PATH)
HYBRID_TEXT_TTS_ENABLED = get_bool(
    "HYBRID_TEXT_TTS_ENABLED", defaults.HYBRID_TEXT_TTS_ENABLED
)
HYBRID_TEXT_TTS_STREAMING = get_bool(
    "HYBRID_TEXT_TTS_STREAMING", defaults.HYBRID_TEXT_TTS_STREAMING
)
HYBRID_LATENCY_PROFILE = get_str(
    "HYBRID_LATENCY_PROFILE", defaults.HYBRID_LATENCY_PROFILE
).lower()
HYBRID_MUTE_MIC_DURING_TTS = get_bool(
    "HYBRID_MUTE_MIC_DURING_TTS", defaults.HYBRID_MUTE_MIC_DURING_TTS
)
HYBRID_RESUME_MIC_AFTER_TTS_DELAY_SEC = get_float(
    "HYBRID_RESUME_MIC_AFTER_TTS_DELAY_SEC",
    defaults.HYBRID_RESUME_MIC_AFTER_TTS_DELAY_SEC,
)
HYBRID_STT_SILENCE_SEC = get_float(
    "HYBRID_STT_SILENCE_SEC", defaults.HYBRID_STT_SILENCE_SEC
)
HYBRID_STT_CONFIRM_SEC = get_float(
    "HYBRID_STT_CONFIRM_SEC", defaults.HYBRID_STT_CONFIRM_SEC
)
HYBRID_STT_REOPEN_SEC = get_float(
    "HYBRID_STT_REOPEN_SEC", defaults.HYBRID_STT_REOPEN_SEC
)
HYBRID_STT_MIN_UTTERANCE_SEC = get_float(
    "HYBRID_STT_MIN_UTTERANCE_SEC", defaults.HYBRID_STT_MIN_UTTERANCE_SEC
)
HYBRID_STT_MAX_COMMAND_SEC = get_float(
    "HYBRID_STT_MAX_COMMAND_SEC", defaults.HYBRID_STT_MAX_COMMAND_SEC
)
HYBRID_STT_FOLLOWUP_TIMEOUT_SEC = get_float(
    "HYBRID_STT_FOLLOWUP_TIMEOUT_SEC", defaults.HYBRID_STT_FOLLOWUP_TIMEOUT_SEC
)
HYBRID_STT_ACCEPT_FINAL_ON_SILENCE = get_bool(
    "HYBRID_STT_ACCEPT_FINAL_ON_SILENCE",
    defaults.HYBRID_STT_ACCEPT_FINAL_ON_SILENCE,
)
HYBRID_STT_DISABLE_REOPEN_AFTER_FINAL = get_bool(
    "HYBRID_STT_DISABLE_REOPEN_AFTER_FINAL",
    defaults.HYBRID_STT_DISABLE_REOPEN_AFTER_FINAL,
)
HYBRID_WEAK_ENDING_ENABLED = get_bool(
    "HYBRID_WEAK_ENDING_ENABLED", defaults.HYBRID_WEAK_ENDING_ENABLED
)
HYBRID_HOLD_WEAK_ENDING_SEC = get_float(
    "HYBRID_HOLD_WEAK_ENDING_SEC", defaults.HYBRID_HOLD_WEAK_ENDING_SEC
)
HYBRID_REJECT_WAKEWORD_ONLY = get_bool(
    "HYBRID_REJECT_WAKEWORD_ONLY", defaults.HYBRID_REJECT_WAKEWORD_ONLY
)
HYBRID_REJECT_TOO_SHORT = get_bool(
    "HYBRID_REJECT_TOO_SHORT", defaults.HYBRID_REJECT_TOO_SHORT
)
CASE_RESPONSE_MODE = get_str(
    "CASE_RESPONSE_MODE", defaults.CASE_RESPONSE_MODE
).lower()
CASE_STREAM_FULL_RESPONSE = get_bool(
    "CASE_STREAM_FULL_RESPONSE", defaults.CASE_STREAM_FULL_RESPONSE
)
CASE_REALTIME_MAX_SENTENCES = get_int(
    "CASE_REALTIME_MAX_SENTENCES", defaults.CASE_REALTIME_MAX_SENTENCES
)
CASE_REALTIME_TARGET_SENTENCES = get_int(
    "CASE_REALTIME_TARGET_SENTENCES", defaults.CASE_REALTIME_TARGET_SENTENCES
)
CASE_REALTIME_MAX_CHARS = get_int(
    "CASE_REALTIME_MAX_CHARS", defaults.CASE_REALTIME_MAX_CHARS
)
CASE_RESPONSE_MAX_TOTAL_CHARS = get_int(
    "CASE_RESPONSE_MAX_TOTAL_CHARS", defaults.CASE_RESPONSE_MAX_TOTAL_CHARS
)
CASE_REALTIME_DETAIL_MAX_CHARS = get_int(
    "CASE_REALTIME_DETAIL_MAX_CHARS", defaults.CASE_REALTIME_DETAIL_MAX_CHARS
)
CASE_REALTIME_DETAIL_MAX_CHUNKS = get_int(
    "CASE_REALTIME_DETAIL_MAX_CHUNKS", defaults.CASE_REALTIME_DETAIL_MAX_CHUNKS
)
CASE_REALTIME_REQUIRE_COMPLETE_SENTENCE = get_bool(
    "CASE_REALTIME_REQUIRE_COMPLETE_SENTENCE",
    defaults.CASE_REALTIME_REQUIRE_COMPLETE_SENTENCE,
)
CASE_REALTIME_JOKE_MAX_CHARS = get_int(
    "CASE_REALTIME_JOKE_MAX_CHARS", defaults.CASE_REALTIME_JOKE_MAX_CHARS
)
CASE_REALTIME_MAX_CHARS_ROAST = get_int(
    "CASE_REALTIME_MAX_CHARS_ROAST", defaults.CASE_REALTIME_MAX_CHARS_ROAST
)
CASE_VOICE_REPLY_MAX_SENTENCES = get_int(
    "CASE_VOICE_REPLY_MAX_SENTENCES", defaults.CASE_VOICE_REPLY_MAX_SENTENCES
)
CASE_VOICE_REPLY_STYLE = get_str(
    "CASE_VOICE_REPLY_STYLE", defaults.CASE_VOICE_REPLY_STYLE
)
CASE_VOICE_JOKE_MAX_SENTENCES = get_int(
    "CASE_VOICE_JOKE_MAX_SENTENCES", defaults.CASE_VOICE_JOKE_MAX_SENTENCES
)
CASE_REALTIME_ALLOW_LONG_ANSWER_WHEN_ASKED = get_bool(
    "CASE_REALTIME_ALLOW_LONG_ANSWER_WHEN_ASKED",
    defaults.CASE_REALTIME_ALLOW_LONG_ANSWER_WHEN_ASKED,
)
CASE_TTS_CHUNK_MODE = get_str(
    "CASE_TTS_CHUNK_MODE",
    get_str("CASE_TTS_CHUNK_POLICY", defaults.CASE_TTS_CHUNK_MODE),
).lower()
CASE_TTS_CHUNK_POLICY = CASE_TTS_CHUNK_MODE
CASE_TTS_REALTIME_MODE = get_str(
    "CASE_TTS_REALTIME_MODE", defaults.CASE_TTS_REALTIME_MODE
).lower()
CASE_TTS_CHUNK_MAX_CHARS = get_int(
    "CASE_TTS_CHUNK_MAX_CHARS", defaults.CASE_TTS_CHUNK_MAX_CHARS
)
CASE_TTS_CHUNK_MIN_CHARS = get_int(
    "CASE_TTS_CHUNK_MIN_CHARS", defaults.CASE_TTS_CHUNK_MIN_CHARS
)
CASE_TTS_MERGE_TINY_CHUNKS = get_bool(
    "CASE_TTS_MERGE_TINY_CHUNKS", defaults.CASE_TTS_MERGE_TINY_CHUNKS
)
CASE_TTS_TINY_CHUNK_MAX_CHARS = get_int(
    "CASE_TTS_TINY_CHUNK_MAX_CHARS", defaults.CASE_TTS_TINY_CHUNK_MAX_CHARS
)
CASE_TTS_SINGLE_CHUNK_UNDER_CHARS = get_int(
    "CASE_TTS_SINGLE_CHUNK_UNDER_CHARS",
    defaults.CASE_TTS_SINGLE_CHUNK_UNDER_CHARS,
)
CASE_TTS_FIRST_CHUNK_TARGET_CHARS = get_int(
    "CASE_TTS_FIRST_CHUNK_TARGET_CHARS",
    defaults.CASE_TTS_FIRST_CHUNK_TARGET_CHARS,
)
CASE_TTS_FIRST_CHUNK_MAX_CHARS = get_int(
    "CASE_TTS_FIRST_CHUNK_MAX_CHARS",
    defaults.CASE_TTS_FIRST_CHUNK_MAX_CHARS,
)
CASE_TTS_NORMAL_CHUNK_TARGET_CHARS = get_int(
    "CASE_TTS_NORMAL_CHUNK_TARGET_CHARS",
    defaults.CASE_TTS_NORMAL_CHUNK_TARGET_CHARS,
)
CASE_TTS_NORMAL_CHUNK_MAX_CHARS = get_int(
    "CASE_TTS_NORMAL_CHUNK_MAX_CHARS",
    defaults.CASE_TTS_NORMAL_CHUNK_MAX_CHARS,
)
CASE_TTS_FLUSH_FIRST_ON_SOFT_PUNCTUATION = get_bool(
    "CASE_TTS_FLUSH_FIRST_ON_SOFT_PUNCTUATION",
    defaults.CASE_TTS_FLUSH_FIRST_ON_SOFT_PUNCTUATION,
)
CASE_TTS_CHUNK_IDEAL_MAX_CHARS = get_int(
    "CASE_TTS_CHUNK_IDEAL_MAX_CHARS", defaults.CASE_TTS_CHUNK_IDEAL_MAX_CHARS
)
CASE_TTS_CHUNK_ABSOLUTE_MAX_CHARS = get_int(
    "CASE_TTS_CHUNK_ABSOLUTE_MAX_CHARS",
    defaults.CASE_TTS_CHUNK_ABSOLUTE_MAX_CHARS,
)
CASE_TTS_CHUNK_PREFER_SENTENCE_BOUNDARY = get_bool(
    "CASE_TTS_CHUNK_PREFER_SENTENCE_BOUNDARY",
    defaults.CASE_TTS_CHUNK_PREFER_SENTENCE_BOUNDARY,
)
CASE_TTS_ALLOW_MULTI_CHUNK = get_bool(
    "CASE_TTS_ALLOW_MULTI_CHUNK", defaults.CASE_TTS_ALLOW_MULTI_CHUNK
)
CASE_TTS_MAX_CHUNKS_PER_TURN = get_int(
    "CASE_TTS_MAX_CHUNKS_PER_TURN", defaults.CASE_TTS_MAX_CHUNKS_PER_TURN
)
CASE_TTS_MAX_CHARS = get_int("CASE_TTS_MAX_CHARS", defaults.CASE_TTS_MAX_CHARS)
CASE_TTS_SYNTH_CONCURRENCY = get_int(
    "CASE_TTS_SYNTH_CONCURRENCY", defaults.CASE_TTS_SYNTH_CONCURRENCY
)
CASE_TTS_PLAYBACK_CONCURRENCY = get_int(
    "CASE_TTS_PLAYBACK_CONCURRENCY", defaults.CASE_TTS_PLAYBACK_CONCURRENCY
)
CASE_TTS_DROP_OLD_TURN_ON_BARGE_IN = get_bool(
    "CASE_TTS_DROP_OLD_TURN_ON_BARGE_IN",
    defaults.CASE_TTS_DROP_OLD_TURN_ON_BARGE_IN,
)
CASE_TTS_MAX_CHUNK_CHARS = get_int(
    "CASE_TTS_MAX_CHUNK_CHARS", defaults.CASE_TTS_MAX_CHUNK_CHARS
)
CASE_TTS_MIN_CHUNK_CHARS = get_int(
    "CASE_TTS_MIN_CHUNK_CHARS", defaults.CASE_TTS_MIN_CHUNK_CHARS
)
CASE_TTS_DROP_OVERFLOW_IN_REALTIME = get_bool(
    "CASE_TTS_DROP_OVERFLOW_IN_REALTIME",
    defaults.CASE_TTS_DROP_OVERFLOW_IN_REALTIME,
)
CASE_TTS_REALTIME_MAX_CHUNKS = get_int(
    "CASE_TTS_REALTIME_MAX_CHUNKS", defaults.CASE_TTS_REALTIME_MAX_CHUNKS
)
CASE_TTS_REALTIME_MAX_CHARS = get_int(
    "CASE_TTS_REALTIME_MAX_CHARS", defaults.CASE_TTS_REALTIME_MAX_CHARS
)
CASE_TTS_REALTIME_MIN_CHARS_BEFORE_SPEAK = get_int(
    "CASE_TTS_REALTIME_MIN_CHARS_BEFORE_SPEAK",
    defaults.CASE_TTS_REALTIME_MIN_CHARS_BEFORE_SPEAK,
)
CASE_TTS_REALTIME_WAIT_FOR_SENTENCE_END = get_bool(
    "CASE_TTS_REALTIME_WAIT_FOR_SENTENCE_END",
    defaults.CASE_TTS_REALTIME_WAIT_FOR_SENTENCE_END,
)
CASE_TTS_REALTIME_TRUNCATE_EXTRA = get_bool(
    "CASE_TTS_REALTIME_TRUNCATE_EXTRA",
    defaults.CASE_TTS_REALTIME_TRUNCATE_EXTRA,
)
CASE_REALTIME_STOP_AFTER_FIRST_SENTENCE = get_bool(
    "CASE_REALTIME_STOP_AFTER_FIRST_SENTENCE",
    defaults.CASE_REALTIME_STOP_AFTER_FIRST_SENTENCE,
)
CASE_REALTIME_TTS_TEXT_DEADLINE_SEC = get_float(
    "CASE_REALTIME_TTS_TEXT_DEADLINE_SEC",
    get_float("CASE_TTS_TEXT_DEADLINE_SEC", defaults.CASE_TTS_TEXT_DEADLINE_SEC),
)
CASE_TTS_REQUIRE_SAFE_BOUNDARY = get_bool(
    "CASE_TTS_REQUIRE_SAFE_BOUNDARY", defaults.CASE_TTS_REQUIRE_SAFE_BOUNDARY
)
CASE_TTS_MIN_SAFE_CHARS = get_int(
    "CASE_TTS_MIN_SAFE_CHARS", defaults.CASE_TTS_MIN_SAFE_CHARS
)
CASE_TTS_MAX_WAIT_FOR_SENTENCE_SEC = get_float(
    "CASE_TTS_MAX_WAIT_FOR_SENTENCE_SEC",
    defaults.CASE_TTS_MAX_WAIT_FOR_SENTENCE_SEC,
)
CASE_TTS_FALLBACK_SHORT_REPLY = get_str(
    "CASE_TTS_FALLBACK_SHORT_REPLY", defaults.CASE_TTS_FALLBACK_SHORT_REPLY
)
CASE_TTS_ENABLE_THINKING_FALLBACK = get_bool(
    "CASE_TTS_ENABLE_THINKING_FALLBACK",
    defaults.CASE_TTS_ENABLE_THINKING_FALLBACK,
)
CASE_TTS_FALLBACK_ONLY_ON_ERROR = get_bool(
    "CASE_TTS_FALLBACK_ONLY_ON_ERROR",
    defaults.CASE_TTS_FALLBACK_ONLY_ON_ERROR,
)
CASE_LLM_FIRST_TOKEN_TIMEOUT_SEC = get_float(
    "CASE_LLM_FIRST_TOKEN_TIMEOUT_SEC",
    get_float("LLM_FIRST_TOKEN_BUDGET_SEC", defaults.CASE_LLM_FIRST_TOKEN_TIMEOUT_SEC),
)
CASE_LLM_STREAM_TOTAL_TIMEOUT_SEC = get_float(
    "CASE_LLM_STREAM_TOTAL_TIMEOUT_SEC",
    get_float("LLM_HARD_TIMEOUT_SEC", defaults.CASE_LLM_STREAM_TOTAL_TIMEOUT_SEC),
)
CASE_LLM_FALLBACK_TO_FULL_ON_FIRST_TOKEN_TIMEOUT = get_bool(
    "CASE_LLM_FALLBACK_TO_FULL_ON_FIRST_TOKEN_TIMEOUT",
    defaults.CASE_LLM_FALLBACK_TO_FULL_ON_FIRST_TOKEN_TIMEOUT,
)
CASE_LLM_ENABLE_WAITING_FILLER = get_bool(
    "CASE_LLM_ENABLE_WAITING_FILLER", defaults.CASE_LLM_ENABLE_WAITING_FILLER
)
CASE_LLM_WAITING_FILLER_TEXT = get_str(
    "CASE_LLM_WAITING_FILLER_TEXT", defaults.CASE_LLM_WAITING_FILLER_TEXT
)
CASE_LLM_WAITING_FILLER_AFTER_SEC = get_float(
    "CASE_LLM_WAITING_FILLER_AFTER_SEC", defaults.CASE_LLM_WAITING_FILLER_AFTER_SEC
)
CASE_ENABLE_THINKING_FILLER = get_bool(
    "CASE_ENABLE_THINKING_FILLER", defaults.CASE_ENABLE_THINKING_FILLER
)
CASE_THINKING_FILLER_AFTER_SEC = get_float(
    "CASE_THINKING_FILLER_AFTER_SEC", defaults.CASE_THINKING_FILLER_AFTER_SEC
)
CASE_THINKING_FILLER_SIMPLE_AFTER_SEC = get_float(
    "CASE_THINKING_FILLER_SIMPLE_AFTER_SEC",
    defaults.CASE_THINKING_FILLER_SIMPLE_AFTER_SEC,
)
CASE_THINKING_FILLER_DIR = get_str(
    "CASE_THINKING_FILLER_DIR", defaults.CASE_THINKING_FILLER_DIR
)
CASE_THINKING_FILLER_MAX_PER_TURN = get_int(
    "CASE_THINKING_FILLER_MAX_PER_TURN",
    defaults.CASE_THINKING_FILLER_MAX_PER_TURN,
)
CASE_THINKING_FILLER_KEYS = [
    item.strip()
    for item in re.split(
        r"[|,]",
        get_str(
            "CASE_THINKING_FILLER_KEYS",
            "|".join(defaults.CASE_THINKING_FILLER_KEYS),
        ),
    )
    if item.strip()
]
CASE_THINKING_FILLER_PREFERRED_KEYS = [
    item.strip()
    for item in re.split(
        r"[|,]",
        get_str(
            "CASE_THINKING_FILLER_PREFERRED_KEYS",
            "|".join(defaults.CASE_THINKING_FILLER_PREFERRED_KEYS),
        ),
    )
    if item.strip()
]
LLM_HARD_TIMEOUT_SEC = CASE_LLM_STREAM_TOTAL_TIMEOUT_SEC
LLM_FIRST_TOKEN_BUDGET_SEC = CASE_LLM_FIRST_TOKEN_TIMEOUT_SEC
CASE_REALTIME_MAX_LLM_WAIT_SEC = get_float(
    "CASE_REALTIME_MAX_LLM_WAIT_SEC",
    defaults.CASE_REALTIME_MAX_LLM_WAIT_SEC,
)
VOICE_ENABLE_AFC = get_bool("VOICE_ENABLE_AFC", defaults.VOICE_ENABLE_AFC)
VOICE_ENABLE_TOOLS_BY_DEFAULT = get_bool(
    "VOICE_ENABLE_TOOLS_BY_DEFAULT", defaults.VOICE_ENABLE_TOOLS_BY_DEFAULT
)
CASE_TTS_PRE_SILENCE_MS = get_int(
    "CASE_TTS_PRE_SILENCE_MS", defaults.CASE_TTS_PRE_SILENCE_MS
)
CASE_TTS_POST_SILENCE_MS = get_int(
    "CASE_TTS_POST_SILENCE_MS", defaults.CASE_TTS_POST_SILENCE_MS
)
CASE_TTS_FADE_IN_MS = get_int("CASE_TTS_FADE_IN_MS", defaults.CASE_TTS_FADE_IN_MS)
CASE_TTS_FADE_OUT_MS = get_int("CASE_TTS_FADE_OUT_MS", defaults.CASE_TTS_FADE_OUT_MS)
CASE_TTS_MIN_UTTERANCE_MS = get_int(
    "CASE_TTS_MIN_UTTERANCE_MS", defaults.CASE_TTS_MIN_UTTERANCE_MS
)
CASE_TTS_DUMP_LAST_UTTERANCE = get_bool(
    "CASE_TTS_DUMP_LAST_UTTERANCE", defaults.CASE_TTS_DUMP_LAST_UTTERANCE
)
CASE_TTS_DEBUG_DIR = get_str("CASE_TTS_DEBUG_DIR", defaults.CASE_TTS_DEBUG_DIR)
CASE_SHOW_LATENCY_SUMMARY = get_bool(
    "CASE_SHOW_LATENCY_SUMMARY", defaults.CASE_SHOW_LATENCY_SUMMARY
)
CASE_TTS_CACHE_ENABLED = get_bool(
    "CASE_TTS_CACHE_ENABLED", defaults.CASE_TTS_CACHE_ENABLED
)
CASE_TTS_CACHE_DIR = get_str("CASE_TTS_CACHE_DIR", defaults.CASE_TTS_CACHE_DIR)
CASE_TTS_CACHE_COMMON_PHRASES = get_bool(
    "CASE_TTS_CACHE_COMMON_PHRASES",
    defaults.CASE_TTS_CACHE_COMMON_PHRASES,
)
CASE_CHECK_PI_THROTTLE = get_bool(
    "CASE_CHECK_PI_THROTTLE", defaults.CASE_CHECK_PI_THROTTLE
)
CASE_VOICE_FX_ENABLED = get_bool(
    "CASE_VOICE_FX_ENABLED", defaults.CASE_VOICE_FX_ENABLED
)
CASE_VOICE_FX_PRESET = get_str(
    "CASE_VOICE_FX_PRESET", defaults.CASE_VOICE_FX_PRESET
)
CASE_VOICE_FX_DUMP_WAV = get_bool(
    "CASE_VOICE_FX_DUMP_WAV", defaults.CASE_VOICE_FX_DUMP_WAV
)
CASE_VOICE_FX_DEBUG_DIR = get_str(
    "CASE_VOICE_FX_DEBUG_DIR", defaults.CASE_VOICE_FX_DEBUG_DIR
)
CASE_VOICE_RESEARCH_DIR = get_str(
    "CASE_VOICE_RESEARCH_DIR", defaults.CASE_VOICE_RESEARCH_DIR
)
CASE_VOICE_SAMPLE_TEXT_SET = get_str(
    "CASE_VOICE_SAMPLE_TEXT_SET", defaults.CASE_VOICE_SAMPLE_TEXT_SET
)
CASE_RECOMMENDED_GEMINI_VOICES = [
    "Schedar", "Algenib", "Orus", "Kore", "Charon", "Rasalgethi"
]

REALTIME_INPUT_SAMPLE_RATE = 16_000
REALTIME_OUTPUT_SAMPLE_RATE = 24_000
REALTIME_AUDIO_FORMAT = "pcm_s16le"
REALTIME_AUDIO_CHUNK_MS = 20

REALTIME_WAKE_ACK_ENABLED = get_bool(
    "REALTIME_WAKE_ACK_ENABLED", defaults.REALTIME_WAKE_ACK_ENABLED
)
REALTIME_WAKE_ACK_TEXT = get_str(
    "REALTIME_WAKE_ACK_TEXT", defaults.REALTIME_WAKE_ACK_TEXT
)
REALTIME_WAKE_ACK_RANDOM_ENABLED = get_bool(
    "REALTIME_WAKE_ACK_RANDOM_ENABLED", defaults.REALTIME_WAKE_ACK_RANDOM_ENABLED
)
REALTIME_WAKE_ACK_POOL = [
    item.strip()
    for item in re.split(
        r"[|,]",
        get_str(
            "REALTIME_WAKE_ACK_POOL",
            "|".join(defaults.REALTIME_WAKE_ACK_POOL),
        ),
    )
    if item.strip()
]
REALTIME_WAKE_ACK_AVOID_REPEAT = get_bool(
    "REALTIME_WAKE_ACK_AVOID_REPEAT", defaults.REALTIME_WAKE_ACK_AVOID_REPEAT
)
WAKE_ACK_RANDOM_ENABLED = get_bool(
    "WAKE_ACK_RANDOM_ENABLED", defaults.WAKE_ACK_RANDOM_ENABLED
)
WAKE_ACK_POOL = [
    item.strip()
    for item in re.split(
        r"[|,]",
        get_str("WAKE_ACK_POOL", "|".join(defaults.WAKE_ACK_POOL)),
    )
    if item.strip()
]
WAKE_ACK_AVOID_REPEAT = get_bool(
    "WAKE_ACK_AVOID_REPEAT", defaults.WAKE_ACK_AVOID_REPEAT
)
WAKE_ACK_ALLOW_SHORT_INTERJECTIONS = get_bool(
    "WAKE_ACK_ALLOW_SHORT_INTERJECTIONS",
    defaults.WAKE_ACK_ALLOW_SHORT_INTERJECTIONS,
)
WAKE_ACK_PROFILE = get_str("WAKE_ACK_PROFILE", defaults.WAKE_ACK_PROFILE)
WAKE_ACK_USE_VOICE_BACKEND = get_bool(
    "WAKE_ACK_USE_VOICE_BACKEND", defaults.WAKE_ACK_USE_VOICE_BACKEND
)
WAKE_ACK_MODE = get_str("WAKE_ACK_MODE", defaults.WAKE_ACK_MODE).lower()
WAKE_ACK_RECORDED_ENABLED = get_bool(
    "WAKE_ACK_RECORDED_ENABLED", defaults.WAKE_ACK_RECORDED_ENABLED
)
WAKE_ACK_RECORDED_DIR = get_str(
    "WAKE_ACK_RECORDED_DIR", defaults.WAKE_ACK_RECORDED_DIR
)
WAKE_ACK_RECORDED_RAW_DIR = get_str(
    "WAKE_ACK_RECORDED_RAW_DIR", defaults.WAKE_ACK_RECORDED_RAW_DIR
)
WAKE_ACK_RECORDED_PROCESSED_DIR = get_str(
    "WAKE_ACK_RECORDED_PROCESSED_DIR",
    defaults.WAKE_ACK_RECORDED_PROCESSED_DIR,
)
WAKE_ACK_FALLBACK_MODE = get_str(
    "WAKE_ACK_FALLBACK_MODE", defaults.WAKE_ACK_FALLBACK_MODE
).lower()
WAKE_ACK_WAV_DIR = get_str(
    "WAKE_ACK_GENERATED_DIR",
    get_str("WAKE_ACK_WAV_DIR", defaults.WAKE_ACK_WAV_DIR),
)
WAKE_ACK_POST_PLAYBACK_PAD_SEC = get_float(
    "WAKE_ACK_POST_PLAYBACK_PAD_SEC", defaults.WAKE_ACK_POST_PLAYBACK_PAD_SEC
)
WAKE_ACK_PAD_SHORT_AUDIO = get_bool(
    "WAKE_ACK_PAD_SHORT_AUDIO", defaults.WAKE_ACK_PAD_SHORT_AUDIO
)
WAKE_ACK_PRE_SILENCE_MS = get_int(
    "WAKE_ACK_PRE_SILENCE_MS", defaults.WAKE_ACK_PRE_SILENCE_MS
)
WAKE_ACK_POST_SILENCE_MS = get_int(
    "WAKE_ACK_POST_SILENCE_MS", defaults.WAKE_ACK_POST_SILENCE_MS
)
WAKE_ACK_FADE_IN_MS = get_int(
    "WAKE_ACK_FADE_IN_MS", defaults.WAKE_ACK_FADE_IN_MS
)
WAKE_ACK_FADE_OUT_MS = get_int(
    "WAKE_ACK_FADE_OUT_MS", defaults.WAKE_ACK_FADE_OUT_MS
)
WAKE_ACK_MIN_DURATION_MS = get_int(
    "WAKE_ACK_MIN_DURATION_MS", defaults.WAKE_ACK_MIN_DURATION_MS
)
WAKE_ACK_MIN_VOICED_MS = get_int(
    "WAKE_ACK_MIN_VOICED_MS", defaults.WAKE_ACK_MIN_VOICED_MS
)
WAKE_ACK_POST_PLAYBACK_GUARD_SEC = get_float(
    "WAKE_ACK_POST_PLAYBACK_GUARD_SEC",
    defaults.WAKE_ACK_POST_PLAYBACK_GUARD_SEC,
)
WAKE_ACK_FORCE_BLOCKING_PLAYBACK = get_bool(
    "WAKE_ACK_FORCE_BLOCKING_PLAYBACK",
    defaults.WAKE_ACK_FORCE_BLOCKING_PLAYBACK,
)
WAKE_ACK_EXTRA_RUNTIME_TAIL_MS = get_int(
    "WAKE_ACK_EXTRA_RUNTIME_TAIL_MS",
    defaults.WAKE_ACK_EXTRA_RUNTIME_TAIL_MS,
)
WAKE_ACK_PLAYBACK_LATENCY = get_str(
    "WAKE_ACK_PLAYBACK_LATENCY", defaults.WAKE_ACK_PLAYBACK_LATENCY
)
AUDIO_PLAYBACK_RETRY_ON_UNDERFLOW = get_bool(
    "AUDIO_PLAYBACK_RETRY_ON_UNDERFLOW",
    defaults.AUDIO_PLAYBACK_RETRY_ON_UNDERFLOW,
)
REALTIME_WAKE_ACK_WAV_DIR = get_str(
    "REALTIME_WAKE_ACK_WAV_DIR", defaults.REALTIME_WAKE_ACK_WAV_DIR
)
REALTIME_WAKE_ACK_MODE = get_str(
    "REALTIME_WAKE_ACK_MODE", WAKE_ACK_MODE
).lower()
REALTIME_WAKE_ACK_WAV_PATH = get_str(
    "REALTIME_WAKE_ACK_WAV_PATH", defaults.REALTIME_WAKE_ACK_WAV_PATH
)
REALTIME_WAKE_ACK_BLOCKS_MIC = get_bool(
    "REALTIME_WAKE_ACK_BLOCKS_MIC", defaults.REALTIME_WAKE_ACK_BLOCKS_MIC
)
REALTIME_WAKE_ACK_CONNECT_IN_PARALLEL = get_bool(
    "REALTIME_WAKE_ACK_CONNECT_IN_PARALLEL",
    defaults.REALTIME_WAKE_ACK_CONNECT_IN_PARALLEL,
)
REALTIME_WAKE_ACK_POST_DELAY_SEC = get_float(
    "REALTIME_WAKE_ACK_POST_DELAY_SEC", defaults.REALTIME_WAKE_ACK_POST_DELAY_SEC
)

REALTIME_HALF_DUPLEX = get_bool("REALTIME_HALF_DUPLEX", defaults.REALTIME_HALF_DUPLEX)
REALTIME_MUTE_MIC_DURING_PLAYBACK = get_bool(
    "REALTIME_MUTE_MIC_DURING_PLAYBACK",
    defaults.REALTIME_MUTE_MIC_DURING_PLAYBACK,
)
REALTIME_RESUME_MIC_AFTER_PLAYBACK_DELAY_SEC = get_float(
    "REALTIME_RESUME_MIC_AFTER_PLAYBACK_DELAY_SEC",
    defaults.REALTIME_RESUME_MIC_AFTER_PLAYBACK_DELAY_SEC,
)
REALTIME_SEND_AUDIO_STREAM_END_ON_MIC_PAUSE = get_bool(
    "REALTIME_SEND_AUDIO_STREAM_END_ON_MIC_PAUSE",
    defaults.REALTIME_SEND_AUDIO_STREAM_END_ON_MIC_PAUSE,
)
REALTIME_MIN_MIC_PAUSE_FOR_STREAM_END_SEC = get_float(
    "REALTIME_MIN_MIC_PAUSE_FOR_STREAM_END_SEC", 1.0
)
REALTIME_IGNORE_ECHO_TRANSCRIPTS = get_bool("REALTIME_IGNORE_ECHO_TRANSCRIPTS", True)
REALTIME_ECHO_TEXT_SIMILARITY_THRESHOLD = get_float(
    "REALTIME_ECHO_TEXT_SIMILARITY_THRESHOLD", 0.70
)
REALTIME_ECHO_TRANSCRIPT_GUARD_SEC = get_float(
    "REALTIME_ECHO_TRANSCRIPT_GUARD_SEC", 2.0
)

REALTIME_ENABLE_TRANSCRIPTS = get_bool("REALTIME_ENABLE_TRANSCRIPTS", True)
REALTIME_ENABLE_BARGE_IN = get_bool(
    "REALTIME_ENABLE_BARGE_IN", defaults.REALTIME_ENABLE_BARGE_IN
)
REALTIME_ENABLE_TOOLS = VOICE_ENABLE_TOOLS_BY_DEFAULT
REALTIME_SESSION_TIMEOUT_SEC = get_float("REALTIME_SESSION_TIMEOUT_SEC", 60.0)
REALTIME_IDLE_END_SEC = get_float("REALTIME_IDLE_END_SEC", 8.0)
REALTIME_LOG_AUDIO_LEVELS = get_bool("REALTIME_LOG_AUDIO_LEVELS", False)
REALTIME_BARGE_IN_MIN_SPEECH_MS = get_int(
    "REALTIME_BARGE_IN_MIN_SPEECH_MS", defaults.REALTIME_BARGE_IN_MIN_SPEECH_MS
)
REALTIME_BARGE_IN_RMS_THRESHOLD = get_float(
    "REALTIME_BARGE_IN_RMS_THRESHOLD", defaults.REALTIME_BARGE_IN_RMS_THRESHOLD
)
REALTIME_BARGE_IN_IGNORE_AFTER_PLAYBACK_START_SEC = get_float(
    "REALTIME_BARGE_IN_IGNORE_AFTER_PLAYBACK_START_SEC",
    defaults.REALTIME_BARGE_IN_IGNORE_AFTER_PLAYBACK_START_SEC,
)
REALTIME_BARGE_IN_COOLDOWN_SEC = get_float(
    "REALTIME_BARGE_IN_COOLDOWN_SEC", defaults.REALTIME_BARGE_IN_COOLDOWN_SEC
)
REALTIME_BARGE_IN_REQUIRE_CONSECUTIVE_FRAMES = get_int(
    "REALTIME_BARGE_IN_REQUIRE_CONSECUTIVE_FRAMES",
    defaults.REALTIME_BARGE_IN_REQUIRE_CONSECUTIVE_FRAMES,
)
REALTIME_BARGE_IN_RMS = REALTIME_BARGE_IN_RMS_THRESHOLD
REALTIME_BARGE_IN_FRAMES = REALTIME_BARGE_IN_REQUIRE_CONSECUTIVE_FRAMES

REALTIME_DUMP_MODEL_AUDIO_WAV = get_bool(
    "REALTIME_DUMP_MODEL_AUDIO_WAV", defaults.REALTIME_DUMP_MODEL_AUDIO_WAV
)
REALTIME_DEBUG_AUDIO_DIR = get_str(
    "REALTIME_DEBUG_AUDIO_DIR", defaults.REALTIME_DEBUG_AUDIO_DIR
)
REALTIME_AUDIO_CHUNK_LOG_INTERVAL_SEC = get_float(
    "REALTIME_AUDIO_CHUNK_LOG_INTERVAL_SEC",
    defaults.REALTIME_AUDIO_CHUNK_LOG_INTERVAL_SEC,
)
REALTIME_STATE_LOG_ON_CHANGE_ONLY = get_bool(
    "REALTIME_STATE_LOG_ON_CHANGE_ONLY", defaults.REALTIME_STATE_LOG_ON_CHANGE_ONLY
)

REALTIME_TOOL_TIMEOUT_SEC = get_float("REALTIME_TOOL_TIMEOUT_SEC", 8.0)
VISION_TOOL_TIMEOUT_SEC = get_float("VISION_TOOL_TIMEOUT_SEC", 6.0)
SNAPSHOT_TOOL_TIMEOUT_SEC = get_float("SNAPSHOT_TOOL_TIMEOUT_SEC", 8.0)


def resolve_voice_mode() -> str:
    """Return a safe runtime mode, falling back to classic when misconfigured."""
    if CASE_VOICE_MODE not in {"classic", "realtime"}:
        logger.warning(
            "Unknown CASE_VOICE_MODE=%r; falling back to classic", CASE_VOICE_MODE
        )
        return "classic"
    if CASE_VOICE_MODE == "realtime" and REALTIME_PROVIDER != "gemini_live":
        logger.warning(
            "Unsupported REALTIME_PROVIDER=%r; falling back to classic",
            REALTIME_PROVIDER,
        )
        return "classic"
    if CASE_VOICE_MODE == "realtime" and not GEMINI_API_KEY:
        logger.warning(
            "CASE_VOICE_MODE=realtime but GEMINI_API_KEY is missing; "
            "falling back to classic"
        )
        return "classic"
    return CASE_VOICE_MODE


def resolve_voice_pipeline() -> str:
    """Return the usable local voice pipeline."""
    if CASE_VOICE_PIPELINE not in {
        "gemini_live_native",
        "hybrid_text_tts",
    }:
        logger.warning(
            "Unknown CASE_VOICE_PIPELINE=%r; using hybrid_text_tts",
            CASE_VOICE_PIPELINE,
        )
        return "hybrid_text_tts"
    if CASE_VOICE_PIPELINE == "hybrid_text_tts":
        if VOICE_OUTPUT_BACKEND == "piper_onnx":
            logger.info("PIPER_ONNX: active for CASE_TTS")
        else:
            logger.info("VOICE_OUTPUT_BACKEND: %s", VOICE_OUTPUT_BACKEND)
        return "hybrid_text_tts"
    return CASE_VOICE_PIPELINE
